//! Rust code of the traits, and the files that hold it.

use std::collections::{BTreeMap, HashMap};

use buffa_codegen::generated::descriptor::{FileDescriptorProto, ServiceDescriptorProto};
use buffa_codegen::idents::make_field_ident;
use proc_macro2::TokenStream;
use quote::{format_ident, quote};

use crate::Error;
use crate::docs::{doc_attrs, method_comment, service_comment};
use crate::methods::{Kind, Method};
use crate::names::{ServiceNames, error_codes, method_name, parameter_name, qualified};
use crate::options::Options;
use crate::paths::path_tokens;
use crate::resolve::TypeResolver;

/// First line of every file the plugin writes.
pub(crate) const HEADER: &str = "// @generated by protoc-gen-contract-rust. DO NOT EDIT.";

/// One output file: its name relative to the `out` directory, and content.
pub(crate) struct OutputFile {
    pub(crate) name: String,
    pub(crate) content: String,
}

/// The traits of every service of `file`.
pub(crate) fn file_code(
    files: &[FileDescriptorProto],
    file: &FileDescriptorProto,
    resolver: &TypeResolver<'_>,
    options: &Options,
) -> Result<String, Error> {
    let rt = path_tokens(&options.runtime)?;
    let mut tokens = TokenStream::new();
    for (index, service) in file.service.iter().enumerate() {
        tokens.extend(service_tokens(
            files, file, index, service, resolver, &rt, options,
        )?);
    }
    let parsed = syn::parse2::<syn::File>(tokens).map_err(|error| {
        Error::new(format!(
            "{}: generated code does not parse ({error}); this is a bug in \
             protoc-gen-contract-rust",
            file.name.as_deref().unwrap_or_default()
        ))
    })?;
    Ok(prettyplease::unparse(&parsed))
}

/// Lay out the per-proto code: one `<stem>.__contract.rs` per proto and a
/// `<pkg>.mod.rs` stitcher per package, or one `<dotted.pkg>.rs` per
/// package under `file_per_package`. `code` holds `(proto path, package,
/// code)` in request order.
pub(crate) fn layout(
    code: Vec<(String, String, String)>,
    file_per_package: bool,
) -> Vec<OutputFile> {
    if file_per_package {
        let mut by_package: BTreeMap<String, String> = BTreeMap::new();
        for (proto, package, code) in code {
            let content = by_package
                .entry(package)
                .or_insert_with(|| format!("{HEADER}\n"));
            content.push_str(&format!("\n// source: {}\n\n{code}", comment_safe(&proto)));
        }
        return by_package
            .into_iter()
            .map(|(package, content)| OutputFile {
                name: buffa_codegen::package_to_filename(&package),
                content,
            })
            .collect();
    }

    let mut files = Vec::with_capacity(code.len());
    let mut stitchers: BTreeMap<String, String> = BTreeMap::new();
    for (proto, package, code) in code {
        let name = format!(
            "{}.__contract.rs",
            buffa_codegen::proto_path_to_stem(&proto)
        );
        // `{:?}` gives a quoted, escaped string literal.
        stitchers
            .entry(package)
            .or_insert_with(|| format!("{HEADER}\n"))
            .push_str(&format!("include!({name:?});\n"));
        files.push(OutputFile {
            name,
            content: format!("{HEADER}\n// source: {}\n\n{code}", comment_safe(&proto)),
        });
    }
    files.extend(stitchers.into_iter().map(|(package, content)| OutputFile {
        name: buffa_codegen::package_to_mod_filename(&package),
        content,
    }));
    files
}

fn service_tokens(
    files: &[FileDescriptorProto],
    file: &FileDescriptorProto,
    index: usize,
    service: &ServiceDescriptorProto,
    resolver: &TypeResolver<'_>,
    rt: &TokenStream,
    options: &Options,
) -> Result<TokenStream, Error> {
    let package = file.package.as_deref().unwrap_or_default();
    let service_name = qualified(package, service.name.as_deref().unwrap_or_default());
    check_methods(&service_name, service)?;

    let names = ServiceNames::of(service);
    let (sync_name, async_name, dyn_name) = (&names.sync, &names.asynchronous, &names.dynamic);
    let comment = service_comment(file, index)
        .map(|comment| format!("{comment}\n\n"))
        .unwrap_or_default();
    let codes = error_codes(files, package, service);
    let fails_with = codes
        .as_ref()
        .map(|codes| {
            format!(
                " It fails with the codes of `{}` (`{}`): branch on them with \
                 `Error::is` or `Error::code_as`.",
                codes.rust_name(),
                codes.qualified
            )
        })
        .unwrap_or_default();
    let sync_doc = doc_attrs(&format!(
        "{comment}Blocking form of `{service_name}`: each method returns when the \
         call is done. Streams are iterators.{fails_with}\n\nImplement it for work that \
         computes; implement `{async_name}` for work that waits on I/O. The trait \
         is dyn-compatible: hold an implementation as `Arc<dyn {sync_name}>` to \
         choose it at run time. `Blocking` gives an `{async_name}` implementation \
         this form."
    ));
    let async_doc = doc_attrs(&format!(
        "{comment}Async form of `{service_name}`: each method returns a future of \
         the result. Streams are `Stream`s.{fails_with}\n\nImplement it with plain `async fn` \
         for work that waits on I/O; implement `{sync_name}` for work that \
         computes. A reply stream must not borrow `self`. Generic callers \
         (`impl {async_name}`) call it without boxing; `{dyn_name}` holds an \
         implementation chosen at run time. `Inline` and `Offload` give a \
         `{sync_name}` implementation this form."
    ));
    let dyn_doc = doc_attrs(&format!(
        "Any `{async_name}` implementation behind dynamic dispatch, for an \
         implementation chosen at run time. It implements `{async_name}` itself, \
         so generic code takes it like any other implementation.\n\nEach call \
         boxes its future, and its reply stream if there is one. Cloning shares \
         the implementation."
    ));

    let sync_trait = format_ident!("{}", sync_name);
    let async_trait = format_ident!("{}", async_name);
    let mut methods = Vec::with_capacity(service.method.len());
    for (method_index, method) in service.method.iter().enumerate() {
        let rpc = method.name.as_deref().unwrap_or_default();
        let kind = Kind::of(method);
        let input = method.input_type.as_deref().unwrap_or_default();
        methods.push(Method {
            kind,
            doc: doc_attrs(
                &method_comment(file, index, method_index)
                    .unwrap_or_else(|| format!("Call `{service_name}.{rpc}`.")),
            ),
            ident: make_field_ident(&method_name(rpc)),
            parameter: make_field_ident(&parameter_name(input, kind.streams_in())),
            request: resolver.rust_type(method.input_type.as_deref().unwrap_or_default())?,
            reply: resolver.rust_type(method.output_type.as_deref().unwrap_or_default())?,
            rt,
            sync_trait: &sync_trait,
            async_trait: &async_trait,
        });
    }
    let sync_decls = methods.iter().map(Method::sync_decl);
    let async_decls = methods.iter().map(Method::async_decl);
    let erased_decls = methods.iter().map(Method::erased_decl);
    let erased_impls = methods.iter().map(Method::erased_impl);
    let dyn_impls = methods.iter().map(Method::dyn_impl);
    let inline_impls = methods.iter().map(Method::inline_impl);
    let offload_impls = methods.iter().map(Method::offload_impl);
    let blocking_impls = methods.iter().map(Method::blocking_impl);

    let dyn_ident = format_ident!("{}", dyn_name);
    let erased_module = format_ident!("{}", names.erased_module);
    let tokio_gate = match &options.tokio_gate {
        Some(feature) => quote!(#[cfg(feature = #feature)]),
        None => TokenStream::new(),
    };
    let alias = match codes.as_ref() {
        Some(codes) => match &codes.alias {
            Some(alias) => {
                let doc = doc_attrs(&format!(
                    "The error codes of `{service_name}`: `{}`, the enum named after \
                     the service. Every implementation reports its failures with \
                     them; a caller branches on them with `Error::is` or \
                     `Error::code_as`.",
                    codes.qualified
                ));
                let ident = format_ident!("{}", alias);
                let target = resolver.rust_type(&codes.fqn)?;
                quote! {
                    #doc
                    pub type #ident = #target;
                }
            }
            None => TokenStream::new(),
        },
        None => TokenStream::new(),
    };
    let send = quote!(::core::marker::Send);
    let sync = quote!(::core::marker::Sync);
    Ok(quote! {
        #sync_doc
        // Method names come from the proto: `IntoX` or `ToX` is a contract's
        // choice, not a conversion.
        #[allow(clippy::wrong_self_convention)]
        pub trait #sync_trait: #send + #sync {
            #(#sync_decls)*
        }

        #async_doc
        #[allow(clippy::wrong_self_convention)]
        pub trait #async_trait: #send + #sync {
            #(#async_decls)*
        }

        #alias

        #dyn_doc
        #[derive(Clone)]
        pub struct #dyn_ident {
            inner: ::std::sync::Arc<dyn #erased_module::Erased>,
        }

        impl ::core::fmt::Debug for #dyn_ident {
            fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                f.debug_struct(#dyn_name).finish_non_exhaustive()
            }
        }

        impl #dyn_ident {
            /// Put `service` behind dynamic dispatch.
            pub fn new<T: #async_trait + 'static>(service: T) -> Self {
                Self { inner: ::std::sync::Arc::new(service) }
            }

            /// Put a shared `service` behind dynamic dispatch.
            pub fn from_arc<T: #async_trait + 'static>(service: ::std::sync::Arc<T>) -> Self {
                Self { inner: service }
            }
        }

        impl #async_trait for #dyn_ident {
            #(#dyn_impls)*
        }

        /// The dyn-compatible face behind the handle: every future and reply
        /// stream boxed.
        #[allow(clippy::type_complexity, clippy::wrong_self_convention)]
        mod #erased_module {
            pub trait Erased: #send + #sync {
                #(#erased_decls)*
            }

            impl<T: super::#async_trait + 'static> Erased for T {
                #(#erased_impls)*
            }
        }

        impl<T: #sync_trait> #async_trait for #rt::Inline<T> {
            #(#inline_impls)*
        }

        #tokio_gate
        impl<T: #sync_trait + 'static> #async_trait for #rt::Offload<T> {
            #(#offload_impls)*
        }

        #tokio_gate
        impl<T: #async_trait + 'static> #sync_trait for #rt::Blocking<T> {
            #(#blocking_impls)*
        }
    })
}

/// `text` for a `//` comment: control characters (a line break would end
/// the comment) are escaped.
fn comment_safe(text: &str) -> String {
    text.chars()
        .flat_map(|c| {
            let escaped: Vec<char> = if c.is_control() {
                c.escape_default().collect()
            } else {
                vec![c]
            };
            escaped
        })
        .collect()
}

/// Refuse methods whose Rust names collide.
fn check_methods(service_name: &str, service: &ServiceDescriptorProto) -> Result<(), Error> {
    let mut seen: HashMap<String, &str> = HashMap::new();
    for method in &service.method {
        let rpc = method.name.as_deref().unwrap_or_default();
        let rust = method_name(rpc);
        if let Some(previous) = seen.insert(rust.clone(), rpc) {
            return Err(Error::new(format!(
                "service {service_name}: methods {previous} and {rpc} both become the \
                 Rust method `{rust}`; rename one of them in the proto"
            )));
        }
    }
    Ok(())
}
