//! The golden output for `proto/`: buffa's messages, connect-rust's service
//! items, and both layouts of Contratto's traits, mounted the ways a
//! consumer crate mounts them.
//!
//! Regenerated by `bazel run //proto:generate`; `bazel test //proto:all`
//! fails while the checked-in files differ from the plugin's output.

/// Messages, from `protoc-gen-buffa` (`buffa_module=crate::proto`).
#[rustfmt::skip]
#[path = "generated/buffa/mod.rs"]
pub mod proto;

/// Traits in the split layout: a file per proto, a stitcher per package.
#[rustfmt::skip]
#[path = "generated/contratto/mod.rs"]
pub mod contract;

/// Traits in the `file_per_package` layout, bridges gated by the `tokio`
/// feature.
pub mod per_package {
    /// Package `example`.
    pub mod example {
        /// Package `example.v1`.
        #[rustfmt::skip]
        pub mod v1 {
            include!("generated/per_package/example.v1.rs");
        }
    }
}

/// All three generators' output in one module per package, the way a crate
/// that `include!`s per-proto files mounts it: no name or impl may clash.
///
/// connect-rust's output is mounted only here: its `Encodable` impls name
/// the `crate::proto` messages, so a second copy would conflict with
/// itself.
pub mod together {
    /// Package `example`.
    pub mod example {
        /// Package `example.common`.
        pub mod common {
            /// Package `example.common.v1`.
            #[rustfmt::skip]
            #[allow(
                non_camel_case_types,
                dead_code,
                unused_imports,
                unused_qualifications,
                clippy::derivable_impls,
                clippy::match_single_binding,
                clippy::uninlined_format_args,
                clippy::doc_lazy_continuation,
                clippy::module_inception
            )]
            pub mod v1 {
                include!("generated/buffa/example.common.v1.mod.rs");
            }
        }

        /// Package `example.shared`.
        pub mod shared {
            /// Package `example.shared.v1`.
            #[rustfmt::skip]
            #[allow(
                non_camel_case_types,
                dead_code,
                unused_imports,
                unused_qualifications,
                clippy::derivable_impls,
                clippy::match_single_binding,
                clippy::uninlined_format_args,
                clippy::doc_lazy_continuation,
                clippy::module_inception
            )]
            pub mod v1 {
                include!("generated/buffa/example.shared.v1.mod.rs");
            }
        }

        /// Package `example.v1`.
        #[rustfmt::skip]
        #[allow(
            non_camel_case_types,
            dead_code,
            unused_imports,
            unused_qualifications,
            clippy::derivable_impls,
            clippy::match_single_binding,
            clippy::uninlined_format_args,
            clippy::doc_lazy_continuation,
            clippy::module_inception,
            // connect-rust's trait method for the RPC `IntoInner`.
            clippy::wrong_self_convention
        )]
        pub mod v1 {
            include!("generated/buffa/example.v1.mod.rs");
            include!("generated/connect/example.v1.counter.__connect.rs");
            include!("generated/connect/example.v1.feed.__connect.rs");
            include!("generated/connect/example.v1.greeter.__connect.rs");
            include!("generated/connect/example.v1.tools.__connect.rs");
            include!("generated/contratto/example.v1.counter.__contratto.rs");
            include!("generated/contratto/example.v1.feed.__contratto.rs");
            include!("generated/contratto/example.v1.greeter.__contratto.rs");
            include!("generated/contratto/example.v1.tools.__contratto.rs");
        }
    }
}

/// The package the golden run maps with `extern_path=.example.shared=crate::shared`.
pub use proto::example::shared;

/// The runtime crate, as the `file_per_package` run names it
/// (`runtime=crate::rt`).
pub use contratto as rt;
