//! The golden output for `proto/`: buffa's messages and both layouts of
//! Contratto's traits, mounted the way a consumer crate mounts them.
//!
//! Regenerated by `bazel run //proto:generate`; `bazel test //proto:all`
//! fails while the checked-in files differ from the plugin's output.

/// Messages, from `protoc-gen-buffa` (`buffa_module=crate::proto`).
#[rustfmt::skip]
#[path = "generated/buffa/mod.rs"]
pub mod proto;

/// Traits in the split layout: a file per proto, a stitcher per package.
#[rustfmt::skip]
#[path = "generated/contratto/mod.rs"]
pub mod contract;

/// Traits in the `file_per_package` layout.
pub mod per_package {
    /// Package `example`.
    pub mod example {
        /// Package `example.v1`.
        #[rustfmt::skip]
        pub mod v1 {
            include!("generated/per_package/example.v1.rs");
        }
    }
}

/// The package the golden run maps with `extern_path=.example.shared=crate::shared`.
pub use proto::example::shared;
