load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

rust_library(
    name = "provider",
    srcs = glob(["src/**/*.rs"]),
    crate_name = "glossary_provider",
    visibility = ["//visibility:public"],
    deps = ["//examples/glossary/api"],
)

rust_test(
    name = "provider_test",
    size = "small",
    crate = ":provider",
    visibility = ["//rust:__pkg__"],
)
