//! Rust code of the traits, and the files that hold it.

use std::collections::{BTreeMap, HashMap};

use buffa_codegen::generated::descriptor::{
    FileDescriptorProto, MethodDescriptorProto, ServiceDescriptorProto,
};
use buffa_codegen::idents::make_field_ident;
use proc_macro2::{Ident, TokenStream};
use quote::{format_ident, quote};

use crate::Error;
use crate::docs::{doc_attrs, method_comment, service_comment};
use crate::names::{ServiceNames, method_name, qualified};
use crate::options::Options;
use crate::paths::path_tokens;
use crate::resolve::TypeResolver;

/// First line of every file the plugin writes.
pub(crate) const HEADER: &str = "// @generated by protoc-gen-contratto-rust. DO NOT EDIT.";

/// One output file: its name relative to the `out` directory, and content.
pub(crate) struct OutputFile {
    pub(crate) name: String,
    pub(crate) content: String,
}

/// The traits of every service of `file`.
pub(crate) fn file_code(
    file: &FileDescriptorProto,
    resolver: &TypeResolver<'_>,
    options: &Options,
) -> Result<String, Error> {
    let rt = path_tokens(&options.runtime)?;
    let mut tokens = TokenStream::new();
    for (index, service) in file.service.iter().enumerate() {
        tokens.extend(service_tokens(file, index, service, resolver, &rt)?);
    }
    let parsed = syn::parse2::<syn::File>(tokens).map_err(|error| {
        Error::new(format!(
            "{}: generated code does not parse ({error}); this is a bug in \
             protoc-gen-contratto-rust",
            file.name.as_deref().unwrap_or_default()
        ))
    })?;
    Ok(prettyplease::unparse(&parsed))
}

/// Lay out the per-proto code: one `<stem>.__contratto.rs` per proto and a
/// `<pkg>.mod.rs` stitcher per package, or one `<dotted.pkg>.rs` per
/// package under `file_per_package`. `code` holds `(proto path, package,
/// code)` in request order.
pub(crate) fn layout(
    code: Vec<(String, String, String)>,
    file_per_package: bool,
) -> Vec<OutputFile> {
    if file_per_package {
        let mut by_package: BTreeMap<String, String> = BTreeMap::new();
        for (proto, package, code) in code {
            let content = by_package
                .entry(package)
                .or_insert_with(|| format!("{HEADER}\n"));
            content.push_str(&format!("\n// source: {proto}\n\n{code}"));
        }
        return by_package
            .into_iter()
            .map(|(package, content)| OutputFile {
                name: buffa_codegen::package_to_filename(&package),
                content,
            })
            .collect();
    }

    let mut files = Vec::with_capacity(code.len());
    let mut stitchers: BTreeMap<String, String> = BTreeMap::new();
    for (proto, package, code) in code {
        let name = format!(
            "{}.__contratto.rs",
            buffa_codegen::proto_path_to_stem(&proto)
        );
        // `{:?}` gives a quoted, escaped string literal.
        stitchers
            .entry(package)
            .or_insert_with(|| format!("{HEADER}\n"))
            .push_str(&format!("include!({name:?});\n"));
        files.push(OutputFile {
            name,
            content: format!("{HEADER}\n// source: {proto}\n\n{code}"),
        });
    }
    files.extend(stitchers.into_iter().map(|(package, content)| OutputFile {
        name: buffa_codegen::package_to_mod_filename(&package),
        content,
    }));
    files
}

/// How a method streams.
#[derive(Clone, Copy)]
enum Kind {
    Unary,
    ServerStreaming,
    ClientStreaming,
    Bidirectional,
}

impl Kind {
    fn of(method: &MethodDescriptorProto) -> Kind {
        match (
            method.client_streaming.unwrap_or(false),
            method.server_streaming.unwrap_or(false),
        ) {
            (false, false) => Kind::Unary,
            (false, true) => Kind::ServerStreaming,
            (true, false) => Kind::ClientStreaming,
            (true, true) => Kind::Bidirectional,
        }
    }
}

/// The tokens one method contributes to each generated item.
struct MethodTokens {
    sync: TokenStream,
    asynchronous: TokenStream,
    erased: TokenStream,
    erased_impl: TokenStream,
    dyn_impl: TokenStream,
}

fn method_tokens(
    kind: Kind,
    doc: &TokenStream,
    ident: &Ident,
    request: &TokenStream,
    reply: &TokenStream,
    async_ident: &Ident,
    rt: &TokenStream,
) -> MethodTokens {
    let result = quote!(::core::result::Result);
    let send = quote!(::core::marker::Send);
    let future = quote!(::core::future::Future);
    let boxed = quote!(::std::boxed::Box::pin);
    let reply_result = quote!(#result<#reply, #rt::Status>);
    let request_item = quote!(#result<#request, #rt::Status>);
    // `R`: the type of an inbound request stream of the async form.
    let inbound = quote! {
        where R: #rt::Stream<Item = #request_item> + #send + 'static
    };
    // The erased form boxes a reply stream after the call resolves.
    let box_stream_after = quote! {
        #boxed(async move {
            let stream = <T as super::#async_ident>::#ident(self, requests).await?;
            #result::Ok(::std::boxed::Box::pin(stream) as #rt::BoxStream<'static, #reply_result>)
        })
    };
    match kind {
        Kind::Unary => MethodTokens {
            sync: quote! {
                #doc
                fn #ident(&self, request: #request) -> #reply_result;
            },
            asynchronous: quote! {
                #doc
                fn #ident(&self, request: #request)
                    -> impl #future<Output = #reply_result> + #send;
            },
            erased: quote! {
                fn #ident(&self, request: #request) -> #rt::BoxFuture<'_, #reply_result>;
            },
            erased_impl: quote! {
                fn #ident(&self, request: #request) -> #rt::BoxFuture<'_, #reply_result> {
                    #boxed(<T as super::#async_ident>::#ident(self, request))
                }
            },
            dyn_impl: quote! {
                fn #ident(&self, request: #request)
                    -> impl #future<Output = #reply_result> + #send {
                    self.inner.#ident(request)
                }
            },
        },
        Kind::ServerStreaming => MethodTokens {
            sync: quote! {
                #doc
                fn #ident(&self, request: #request)
                    -> #result<#rt::BoxIter<'_, #reply_result>, #rt::Status>;
            },
            asynchronous: quote! {
                #doc
                fn #ident(&self, request: #request) -> impl #future<
                    Output = #result<
                        impl #rt::Stream<Item = #reply_result> + #send + use<Self>,
                        #rt::Status,
                    >,
                > + #send;
            },
            erased: quote! {
                fn #ident(&self, request: #request) -> #rt::BoxFuture<
                    '_,
                    #result<#rt::BoxStream<'static, #reply_result>, #rt::Status>,
                >;
            },
            erased_impl: {
                let body = quote! {
                    #boxed(async move {
                        let stream = <T as super::#async_ident>::#ident(self, request).await?;
                        #result::Ok(::std::boxed::Box::pin(stream) as #rt::BoxStream<'static, #reply_result>)
                    })
                };
                quote! {
                    fn #ident(&self, request: #request) -> #rt::BoxFuture<
                        '_,
                        #result<#rt::BoxStream<'static, #reply_result>, #rt::Status>,
                    > {
                        #body
                    }
                }
            },
            dyn_impl: quote! {
                fn #ident(&self, request: #request) -> impl #future<
                    Output = #result<
                        impl #rt::Stream<Item = #reply_result> + #send + use<>,
                        #rt::Status,
                    >,
                > + #send {
                    self.inner.#ident(request)
                }
            },
        },
        Kind::ClientStreaming => MethodTokens {
            sync: quote! {
                #doc
                fn #ident(&self, requests: #rt::BoxIter<'_, #request_item>) -> #reply_result;
            },
            asynchronous: quote! {
                #doc
                fn #ident<R>(&self, requests: R) -> impl #future<Output = #reply_result> + #send
                #inbound;
            },
            erased: quote! {
                fn #ident(&self, requests: #rt::BoxStream<'static, #request_item>)
                    -> #rt::BoxFuture<'_, #reply_result>;
            },
            erased_impl: quote! {
                fn #ident(&self, requests: #rt::BoxStream<'static, #request_item>)
                    -> #rt::BoxFuture<'_, #reply_result> {
                    #boxed(<T as super::#async_ident>::#ident(self, requests))
                }
            },
            dyn_impl: quote! {
                fn #ident<R>(&self, requests: R) -> impl #future<Output = #reply_result> + #send
                #inbound
                {
                    self.inner.#ident(::std::boxed::Box::pin(requests))
                }
            },
        },
        Kind::Bidirectional => MethodTokens {
            sync: quote! {
                #doc
                fn #ident<'a>(&'a self, requests: #rt::BoxIter<'a, #request_item>)
                    -> #result<#rt::BoxIter<'a, #reply_result>, #rt::Status>;
            },
            asynchronous: quote! {
                #doc
                fn #ident<R>(&self, requests: R) -> impl #future<
                    Output = #result<
                        impl #rt::Stream<Item = #reply_result> + #send + use<Self, R>,
                        #rt::Status,
                    >,
                > + #send
                #inbound;
            },
            erased: quote! {
                fn #ident(&self, requests: #rt::BoxStream<'static, #request_item>) -> #rt::BoxFuture<
                    '_,
                    #result<#rt::BoxStream<'static, #reply_result>, #rt::Status>,
                >;
            },
            erased_impl: quote! {
                fn #ident(&self, requests: #rt::BoxStream<'static, #request_item>) -> #rt::BoxFuture<
                    '_,
                    #result<#rt::BoxStream<'static, #reply_result>, #rt::Status>,
                > {
                    #box_stream_after
                }
            },
            dyn_impl: quote! {
                fn #ident<R>(&self, requests: R) -> impl #future<
                    Output = #result<
                        impl #rt::Stream<Item = #reply_result> + #send + use<R>,
                        #rt::Status,
                    >,
                > + #send
                #inbound
                {
                    self.inner.#ident(::std::boxed::Box::pin(requests))
                }
            },
        },
    }
}

fn service_tokens(
    file: &FileDescriptorProto,
    index: usize,
    service: &ServiceDescriptorProto,
    resolver: &TypeResolver<'_>,
    rt: &TokenStream,
) -> Result<TokenStream, Error> {
    let package = file.package.as_deref().unwrap_or_default();
    let service_name = qualified(package, service.name.as_deref().unwrap_or_default());
    check_methods(&service_name, service)?;

    let names = ServiceNames::of(service);
    let (sync_name, async_name, dyn_name) = (&names.sync, &names.asynchronous, &names.dynamic);
    let comment = service_comment(file, index)
        .map(|comment| format!("{comment}\n\n"))
        .unwrap_or_default();
    let sync_doc = doc_attrs(&format!(
        "{comment}Blocking form of `{service_name}`: each method returns when the \
         call is done. Streams are iterators.\n\nImplement it for work that \
         computes; implement `{async_name}` for work that waits on I/O. The trait \
         is dyn-compatible: hold an implementation as `Arc<dyn {sync_name}>` to \
         choose it at run time."
    ));
    let async_doc = doc_attrs(&format!(
        "{comment}Async form of `{service_name}`: each method returns a future of \
         the result. Streams are `Stream`s.\n\nImplement it with plain `async fn` \
         for work that waits on I/O; implement `{sync_name}` for work that \
         computes. A reply stream must not borrow `self`. Generic callers \
         (`impl {async_name}`) call it without boxing; `{dyn_name}` holds an \
         implementation chosen at run time."
    ));
    let dyn_doc = doc_attrs(&format!(
        "Any `{async_name}` implementation behind dynamic dispatch, for an \
         implementation chosen at run time. It implements `{async_name}` itself, \
         so generic code takes it like any other implementation.\n\nEach call \
         boxes its future, and its reply stream if there is one. Cloning shares \
         the implementation."
    ));

    let async_ident = format_ident!("{}", async_name);
    let mut tokens: Vec<MethodTokens> = Vec::with_capacity(service.method.len());
    for (method_index, method) in service.method.iter().enumerate() {
        let rpc = method.name.as_deref().unwrap_or_default();
        let ident = make_field_ident(&method_name(rpc));
        let request = resolver.rust_type(method.input_type.as_deref().unwrap_or_default())?;
        let reply = resolver.rust_type(method.output_type.as_deref().unwrap_or_default())?;
        let doc = doc_attrs(
            &method_comment(file, index, method_index)
                .unwrap_or_else(|| format!("Call `{service_name}.{rpc}`.")),
        );
        tokens.push(method_tokens(
            Kind::of(method),
            &doc,
            &ident,
            &request,
            &reply,
            &async_ident,
            rt,
        ));
    }
    let sync_methods = tokens.iter().map(|m| &m.sync);
    let async_methods = tokens.iter().map(|m| &m.asynchronous);
    let erased_methods = tokens.iter().map(|m| &m.erased);
    let erased_impls = tokens.iter().map(|m| &m.erased_impl);
    let dyn_impls = tokens.iter().map(|m| &m.dyn_impl);

    let sync_ident = format_ident!("{}", sync_name);
    let dyn_ident = format_ident!("{}", dyn_name);
    let erased_module = format_ident!("{}", names.erased_module);
    let send = quote!(::core::marker::Send);
    let sync = quote!(::core::marker::Sync);
    Ok(quote! {
        #sync_doc
        pub trait #sync_ident: #send + #sync {
            #(#sync_methods)*
        }

        #async_doc
        pub trait #async_ident: #send + #sync {
            #(#async_methods)*
        }

        #dyn_doc
        #[derive(Clone)]
        pub struct #dyn_ident {
            inner: ::std::sync::Arc<dyn #erased_module::Erased>,
        }

        impl #dyn_ident {
            /// Put `service` behind dynamic dispatch.
            pub fn new<T: #async_ident + 'static>(service: T) -> Self {
                Self { inner: ::std::sync::Arc::new(service) }
            }

            /// Put a shared `service` behind dynamic dispatch.
            pub fn from_arc<T: #async_ident + 'static>(service: ::std::sync::Arc<T>) -> Self {
                Self { inner: service }
            }
        }

        impl #async_ident for #dyn_ident {
            #(#dyn_impls)*
        }

        /// The dyn-compatible face behind the handle: every future and reply
        /// stream boxed.
        #[allow(clippy::type_complexity)]
        mod #erased_module {
            pub trait Erased: #send + #sync {
                #(#erased_methods)*
            }

            impl<T: super::#async_ident + 'static> Erased for T {
                #(#erased_impls)*
            }
        }
    })
}

/// Refuse methods whose Rust names collide.
fn check_methods(service_name: &str, service: &ServiceDescriptorProto) -> Result<(), Error> {
    let mut seen: HashMap<String, &str> = HashMap::new();
    for method in &service.method {
        let rpc = method.name.as_deref().unwrap_or_default();
        let rust = method_name(rpc);
        if let Some(previous) = seen.insert(rust.clone(), rpc) {
            return Err(Error::new(format!(
                "service {service_name}: methods {previous} and {rpc} both become the \
                 Rust method `{rust}`; rename one of them in the proto"
            )));
        }
    }
    Ok(())
}
