load("@rules_rust//rust:defs.bzl", "rust_binary", "rust_test")

rust_binary(
    name = "app",
    srcs = glob(["src/**/*.rs"]),
    crate_name = "glossary_app",
    visibility = ["//rust:__pkg__"],
    deps = [
        "//examples/glossary/api",
        "//examples/glossary/consumer",
        "//examples/glossary/provider",
    ],
)

rust_test(
    name = "app_test",
    size = "small",
    crate = ":app",
    visibility = ["//rust:__pkg__"],
)
