load("@bazel_utils_rust//:rust.bzl", "cargo_audit_test")
load("@rules_rust//rust:defs.bzl", "rust_clippy_test")
load("//bazel:compat.bzl", "NOT_WINDOWS")

rust_clippy_test(
    name = "lint",
    size = "small",
    targets = [
        "//rust/contract",
        "//rust/contract:contract_no_tokio",
        "//rust/contract:contract_no_tokio_test",
        "//rust/contract:contract_test",
        "//rust/golden",
        "//rust/golden:golden_no_tokio",
        "//rust/golden:bridges_test",
        "//rust/golden:direct_test",
        "//rust/golden:streaming_test",
        "//rust/protoc-gen-contract-rust",
        "//rust/protoc-gen-contract-rust:lib",
        "//rust/protoc-gen-contract-rust:lib_test",
    ],
)

cargo_audit_test(
    name = "vuln",
    size = "small",
    target_compatible_with = NOT_WINDOWS,
)
