load("@rules_rust//rust:defs.bzl", "rust_library")

exports_files([
    "Cargo.toml",
    # Destination of //examples/glossary:generate.
    "src/generated",
])

rust_library(
    name = "api",
    srcs = glob(["src/**/*.rs"]),
    crate_name = "glossary_api",
    visibility = ["//visibility:public"],
    deps = [
        "//rust/protocontract",
        "@contract_cargo//:buffa",
    ],
)
