load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

rust_library(
    name = "consumer",
    srcs = glob(["src/**/*.rs"]),
    crate_name = "glossary_consumer",
    visibility = ["//visibility:public"],
    deps = ["//examples/glossary/api"],
)

rust_test(
    name = "consumer_test",
    size = "small",
    crate = ":consumer",
    visibility = ["//rust:__pkg__"],
)
